const MOLD_DATA = [
  { domain: "시트/칵핏", system: "시트", modular: "FR SEAT", part: "Seat Frame", spec: "Standard", cost: 50, totalCost: 100, models: { NE2: "신규", NV1: "NE2", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "FR SEAT", part: "Seat Frame", spec: "Light-Weight", cost: 65, totalCost: 65, models: { NE2: "-", NV1: "-", JK2: "-", JW2: "-", ME2: "신규", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "FR SEAT", part: "Cushion Foam", spec: "Memory Foam", cost: 15, totalCost: 15, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "FR SEAT", part: "Slide Rail", spec: "Electric", cost: 25, totalCost: 25, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "FR SEAT", part: "Headrest", spec: "Active-Type", cost: 18, totalCost: 18, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "RR SEAT", part: "Rear Frame", spec: "6:4 Foldable", cost: 80, totalCost: 80, models: { NE2: "신규", NV1: "NE2", JK2: "NV1", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "RR SEAT", part: "Center Armrest", spec: "Integrated", cost: 30, totalCost: 30, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modular: "RR SEAT", part: "ISOFIX Bracket", spec: "Steel", cost: 10, totalCost: 10, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "IP MODULE", part: "Main IP Panel", spec: "Soft-Pad", cost: 120, totalCost: 120, models: { NE2: "신규", NV1: "NE2", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "IP MODULE", part: "Glove Box", spec: "Damping-Type", cost: 40, totalCost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "IP MODULE", part: "Air Vent", spec: "Slim-Design", cost: 35, totalCost: 35, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "IP MODULE", part: "Cluster Housing", spec: "12.3-inch", cost: 45, totalCost: 45, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "CONSOLE", part: "Console Body", spec: "Sliding-Type", cost: 95, totalCost: 95, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "CONSOLE", part: "Shift Bezel", spec: "Piano Black", cost: 15, totalCost: 15, models: { NE2: "신규", NV1: "NE2", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "CONSOLE", part: "Cup Holder", spec: "Open-Type", cost: 12, totalCost: 12, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "CONSOLE", part: "Armrest Cover", spec: "Leather", cost: 22, totalCost: 22, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "DOOR TRIM", part: "Main Panel", spec: "Recycled-PET", cost: 100, totalCost: 100, models: { NE2: "신규", NV1: "NE2", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "DOOR TRIM", part: "Armrest Support", spec: "Reinforced", cost: 35, totalCost: 35, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "DOOR TRIM", part: "Switch Bezel", spec: "Silver-Paint", cost: 20, totalCost: 20, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modular: "DOOR TRIM", part: "Speaker Grille", spec: "Metal-Etching", cost: 38, totalCost: 38, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "HEAD LAMP", part: "LED Module", spec: "Matrix LED", cost: 200, totalCost: 200, models: { NE2: "신규", NV1: "NE2", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "HEAD LAMP", part: "LED Module", spec: "Basic LED", cost: 150, totalCost: 0, models: { NE2: "-", NV1: "-", JK2: "NV1", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "HEAD LAMP", part: "Housing", spec: "Light-Weight", cost: 80, totalCost: 80, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "HEAD LAMP", part: "Lens", spec: "Clear Type", cost: 60, totalCost: 60, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "REAR COMB LAMP", part: "Outer Lens", spec: "Full Red", cost: 90, totalCost: 90, models: { NE2: "신규", NV1: "NE2", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "REAR COMB LAMP", part: "Inner Lens", spec: "Diffusion", cost: 55, totalCost: 55, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "REAR COMB LAMP", part: "PCB Ass'y", spec: "Multi-Function", cost: 110, totalCost: 110, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "REAR COMB LAMP", part: "Housing", spec: "Standard", cost: 70, totalCost: 70, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "INTERIOR LAMP", part: "Mood Light LED", spec: "RGB Color", cost: 45, totalCost: 45, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "INTERIOR LAMP", part: "Mood Light LED", spec: "Single White", cost: 25, totalCost: 25, models: { NE2: "-", NV1: "-", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "INTERIOR LAMP", part: "Door Spot Lamp", spec: "Logo Projection", cost: 35, totalCost: 35, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "INTERIOR LAMP", part: "Room Lamp", spec: "Touch Sensor", cost: 50, totalCost: 50, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "INTERIOR LAMP", part: "Roof Light", spec: "LED Strip", cost: 40, totalCost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "SIDE MIRROR", part: "Mirror Glass", spec: "ECM Type", cost: 40, totalCost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "SIDE MIRROR", part: "Actuator", spec: "Power Fold", cost: 85, totalCost: 85, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "SIDE MIRROR", part: "Side Repeater", spec: "Sequential", cost: 55, totalCost: 55, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "SIDE MIRROR", part: "Main Body", spec: "Standard", cost: 95, totalCost: 95, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "SIDE MIRROR", part: "Base Plate", spec: "Reinforced", cost: 40, totalCost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "FOG LAMP", part: "Projection Lens", spec: "Wide View", cost: 50, totalCost: 50, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "FOG LAMP", part: "LED Unit", spec: "Vertical Type", cost: 65, totalCost: 65, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "FOG LAMP", part: "LED Unit", spec: "Horizontal Type", cost: 60, totalCost: 0, models: { NE2: "-", NV1: "-", JK2: "NV1", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "FOG LAMP", part: "Bracket", spec: "Standard", cost: 20, totalCost: 20, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modular: "FOG LAMP", part: "Bezel", spec: "Black High-Gloss", cost: 30, totalCost: 30, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } }
];