const MOLD_DATA = [
  { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Seat Frame", spec: "Standard", cost: 50, models: { NE2: "신규", NV1: "공용", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Seat Frame", spec: "Light-Weight", cost: 65, models: { NE2: "-", NV1: "-", JK2: "-", JW2: "-", ME2: "신규", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Cushion Foam", spec: "Memory Foam", cost: 15, models: { NE2: "신규", NV1: "-", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Slide Rail", spec: "Electric", cost: 25, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "공용", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Headrest", spec: "Active-Type", cost: 18, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "공용", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "RR SEAT", part: "Rear Frame", spec: "6:4 Foldable", cost: 80, models: { NE2: "신규", NV1: "공용", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "RR SEAT", part: "Center Armrest", spec: "Integrated", cost: 30, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "시트", modularSystem: "RR SEAT", part: "ISOFIX Bracket", spec: "Steel", cost: 10, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "IP MODULE", part: "Main IP Panel", spec: "Soft-Pad", cost: 120, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "IP MODULE", part: "Glove Box", spec: "Damping-Type", cost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "IP MODULE", part: "Air Vent", spec: "Slim-Design", cost: 35, models: { NE2: "신규", NV1: "-", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "IP MODULE", part: "Cluster Housing", spec: "12.3-inch", cost: 45, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "CONSOLE", part: "Console Body", spec: "Sliding-Type", cost: 95, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "CONSOLE", part: "Shift Bezel", spec: "Piano Black", cost: 15, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "CONSOLE", part: "Cup Holder", spec: "Open-Type", cost: 12, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "공용", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "CONSOLE", part: "Armrest Cover", spec: "Leather", cost: 22, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "DOOR TRIM", part: "Main Panel", spec: "Recycled-PET", cost: 100, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "DOOR TRIM", part: "Armrest Support", spec: "Reinforced", cost: 35, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "DOOR TRIM", part: "Switch Bezel", spec: "Silver-Paint", cost: 20, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "시트/칵핏", system: "칵핏", modularSystem: "DOOR TRIM", part: "Speaker Grille", spec: "Metal-Etching", cost: 38, models: { NE2: "신규", NV1: "-", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "HEAD LAMP", part: "LED Module", spec: "Matrix LED", cost: 200, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "HEAD LAMP", part: "LED Module", spec: "Basic LED", cost: 150, models: { NE2: "-", NV1: "-", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "HEAD LAMP", part: "Housing", spec: "Light-Weight", cost: 80, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "HEAD LAMP", part: "Lens", spec: "Clear Type", cost: 60, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "REAR COMB LAMP", part: "Outer Lens", spec: "Full Red", cost: 90, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "REAR COMB LAMP", part: "Inner Lens", spec: "Diffusion", cost: 55, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "REAR COMB LAMP", part: "PCB Ass'y", spec: "Multi-Function", cost: 110, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "REAR COMB LAMP", part: "Housing", spec: "Standard", cost: 70, models: { NE2: "신규", NV1: "-", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "INTERIOR LAMP", part: "Mood Light LED", spec: "RGB Color", cost: 45, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "INTERIOR LAMP", part: "Mood Light LED", spec: "Single White", cost: 25, models: { NE2: "-", NV1: "-", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "INTERIOR LAMP", part: "Door Spot Lamp", spec: "Logo Projection", cost: 35, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "공용", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "INTERIOR LAMP", part: "Room Lamp", spec: "Touch Sensor", cost: 50, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "공용", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "INTERIOR LAMP", part: "Roof Light", spec: "LED Strip", cost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "SIDE MIRROR", part: "Mirror Glass", spec: "ECM Type", cost: 40, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "SIDE MIRROR", part: "Actuator", spec: "Power Fold", cost: 85, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "SIDE MIRROR", part: "Side Repeater", spec: "Sequential", cost: 55, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "램프", modularSystem: "SIDE MIRROR", part: "Main Body", spec: "Standard", cost: 95, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "전장", modularSystem: "BCM", part: "BCM Module", spec: "Gen4", cost: 180, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "전장", modularSystem: "BCM", part: "Wiring Harness", spec: "Main", cost: 150, models: { NE2: "신규", NV1: "-", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "전장", modularSystem: "SENSOR", part: "ADAS Camera", spec: "Front Wide", cost: 220, models: { NE2: "신규", NV1: "공용", JK2: "공용", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "전장", modularSystem: "SENSOR", part: "Radar Sensor", spec: "77GHz", cost: 190, models: { NE2: "신규", NV1: "-", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "전장/편의", system: "전장", modularSystem: "SENSOR", part: "Ultrasonic Sensor", spec: "Park Assist", cost: 30, models: { NE2: "신규", NV1: "공용", JK2: "공용", JW2: "공용", ME2: "-", MV2: "-" } },
  { domain: "샤시/외장", system: "샤시", modularSystem: "SUSPENSION", part: "Front Strut", spec: "Sports Tuning", cost: 130, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "신규", MV2: "-" } },
  { domain: "샤시/외장", system: "샤시", modularSystem: "SUSPENSION", part: "Rear Multi-link", spec: "Standard", cost: 160, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "공용", MV2: "-" } },
  { domain: "샤시/외장", system: "샤시", modularSystem: "BRAKE", part: "Front Caliper", spec: "4-Piston", cost: 110, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "-", ME2: "-", MV2: "신규" } },
  { domain: "샤시/외장", system: "샤시", modularSystem: "BRAKE", part: "Rear Disc", spec: "Ventilated", cost: 75, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "-", ME2: "-", MV2: "공용" } },
  { domain: "샤시/외장", system: "외장", modularSystem: "BUMPER", part: "Front Bumper Fascia", spec: "Standard", cost: 85, models: { NE2: "신규", NV1: "-", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "샤시/외장", system: "외장", modularSystem: "BUMPER", part: "Rear Bumper Fascia", spec: "Standard", cost: 80, models: { NE2: "신규", NV1: "-", JK2: "신규", JW2: "-", ME2: "-", MV2: "-" } },
  { domain: "샤시/외장", system: "외장", modularSystem: "BODY PANEL", part: "Hood Panel", spec: "Aluminum", cost: 120, models: { NE2: "신규", NV1: "-", JK2: "-", JW2: "신규", ME2: "-", MV2: "-" } },
  { domain: "샤시/외장", system: "외장", modularSystem: "BODY PANEL", part: "Front Fender", spec: "Steel", cost: 65, models: { NE2: "신규", NV1: "공용", JK2: "-", JW2: "공용", ME2: "-", MV2: "-" } },
];
