const partsData = [
    { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Front Seat Frame", spec: "Leather-Type A", moldCost: 30, targetVehicle: "EV6", sharedVehicle: "IONIQ5, EV6" },
    { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Front Seat Frame", spec: "Fabric-Type B", moldCost: 30, targetVehicle: "EV6", sharedVehicle: "EV6" },
    { domain: "시트/칵핏", system: "시트", modularSystem: "RR SEAT", part: "Rear Seat Cushion", spec: "Standard", moldCost: 45, targetVehicle: "EV6", sharedVehicle: "IONIQ5, EV6, GV60" },
    { domain: "시트/칵핏", system: "칵핏모듈", modularSystem: "IP MODULE", part: "Main Board", spec: "12.3-inch", moldCost: 120, targetVehicle: "K8", sharedVehicle: "K8, K9" },
    { domain: "시트/칵핏", system: "칵핏모듈", modularSystem: "IP MODULE", part: "Main Board", spec: "10.25-inch", moldCost: 120, targetVehicle: "K8", sharedVehicle: "K8, K5" },
    { domain: "전장", system: "AVN", modularSystem: "HEAD UNIT", part: "Display Panel", spec: "Curved Display", moldCost: 200, targetVehicle: "EV9", sharedVehicle: "EV9, IONIQ7" },
    { domain: "전장", system: "AVN", modularSystem: "HEAD UNIT", part: "Housing Case", spec: "Plastic-Black", moldCost: 15, targetVehicle: "EV9", sharedVehicle: "EV9, EV6" },
    { domain: "파워트레인", system: "인버터", modularSystem: "PCU", part: "Power Module", spec: "800V High Power", moldCost: 350, targetVehicle: "IONIQ6", sharedVehicle: "IONIQ6, IONIQ5, EV6" },
    { domain: "파워트레인", system: "인버터", modularSystem: "PCU", part: "DC-DC Converter", spec: "Standard", moldCost: 85, targetVehicle: "IONIQ6", sharedVehicle: "IONIQ6" },
    { domain: "섀시", system: "제동", modularSystem: "ABS MODULE", part: "Valve Block", spec: "Aluminum-L4", moldCost: 55, targetVehicle: "GV70", sharedVehicle: "GV70, GV80" },
    { domain: "섀시", system: "제동", modularSystem: "ABS MODULE", part: "Electronic Motor", spec: "12V-High", moldCost: 42, targetVehicle: "GV70", sharedVehicle: "GV70, GV60" },
    { domain: "섀시", system: "현가", modularSystem: "AIR SUS", part: "Air Spring Case", spec: "Multi-Chamber", moldCost: 95, targetVehicle: "G90", sharedVehicle: "G90" },
    { domain: "섀시", system: "현가", modularSystem: "AIR SUS", part: "Compressor Bracket", spec: "Steel-ST12", moldCost: 12, targetVehicle: "G90", sharedVehicle: "G90, G80" },
    { domain: "의장", system: "도어트림", modularSystem: "DOOR MODULE", part: "Armrest Support", spec: "Soft-Touch", moldCost: 28, targetVehicle: "K5", sharedVehicle: "K5, SONATA" },
    { domain: "의장", system: "도어트림", modularSystem: "DOOR MODULE", part: "Speaker Grille", spec: "Metal-Etching", moldCost: 18, targetVehicle: "K5", sharedVehicle: "K5, K8" },
    { domain: "바디", system: "후드", modularSystem: "FRONT BODY", part: "Hood Inner Panel", spec: "Aluminum-AL5052", moldCost: 180, targetVehicle: "EV6", sharedVehicle: "EV6" },
    { domain: "바디", system: "후드", modularSystem: "FRONT BODY", part: "Hood Outer Panel", spec: "Steel-SGC", moldCost: 220, targetVehicle: "EV6", sharedVehicle: "EV6" },
    { domain: "바디", system: "사이드", modularSystem: "SIDE STRUCTURE", part: "Center Pillar", spec: "Hot Stamping", moldCost: 150, targetVehicle: "Sorento", sharedVehicle: "Sorento, Santa Fe" },
    { domain: "바디", system: "사이드", modularSystem: "SIDE STRUCTURE", part: "Side Sill", spec: "Steel-High Tensile", moldCost: 130, targetVehicle: "Sorento", sharedVehicle: "Sorento" },
    { domain: "공조", system: "HVAC", modularSystem: "AIR CONDITIONING", part: "Evaporator Case", spec: "Plastic-PP", moldCost: 45, targetVehicle: "Avante", sharedVehicle: "Avante, K3" },
    { domain: "공조", system: "HVAC", modularSystem: "AIR CONDITIONING", part: "Blower Fan", spec: "Quiet-Type", moldCost: 22, targetVehicle: "Avante", sharedVehicle: "Avante" },
    { domain: "공조", system: "HVAC", modularSystem: "PTC HEATER", part: "Heating Element", spec: "5kW-High", moldCost: 65, targetVehicle: "EV6", sharedVehicle: "EV6, IONIQ5" },
    { domain: "램프", system: "헤드램프", modularSystem: "FRONT LIGHTING", part: "Lens Cover", spec: "PC-Clear", moldCost: 110, targetVehicle: "Grandeur", sharedVehicle: "Grandeur" },
    { domain: "램프", system: "헤드램프", modularSystem: "FRONT LIGHTING", part: "LED Module Case", spec: "Aluminum-Diecast", moldCost: 75, targetVehicle: "Grandeur", sharedVehicle: "Grandeur, K8" },
    { domain: "램프", system: "리어램프", modularSystem: "REAR LIGHTING", part: "Outer Lens", spec: "Red-Tinted", moldCost: 90, targetVehicle: "Grandeur", sharedVehicle: "Grandeur" },
    { domain: "전장", system: "ADAS", modularSystem: "FRONT CAMERA", part: "Camera Bracket", spec: "Glass-Fiber-PA", moldCost: 12, targetVehicle: "GV80", sharedVehicle: "GV80, GV70" },
    { domain: "전장", system: "ADAS", modularSystem: "FRONT CAMERA", part: "Processing Unit Case", spec: "Aluminum", moldCost: 35, targetVehicle: "GV80", sharedVehicle: "GV80" },
    { domain: "전장", system: "ADAS", modularSystem: "RADAR", part: "Sensor Cover", spec: "Radome-ABS", moldCost: 20, targetVehicle: "GV80", sharedVehicle: "GV80, G80" },
    { domain: "구동", system: "감속기", modularSystem: "EDU", part: "Gear Housing", spec: "Aluminum-ALDC12", moldCost: 280, targetVehicle: "IONIQ5", sharedVehicle: "IONIQ5, EV6" },
    { domain: "구동", system: "감속기", modularSystem: "EDU", part: "Main Shaft", spec: "Steel-Forged", moldCost: 150, targetVehicle: "IONIQ5", sharedVehicle: "IONIQ5" },
    { domain: "배터리", system: "BPA", modularSystem: "BATTERY PACK", part: "Lower Case", spec: "Aluminum-Extrusion", moldCost: 450, targetVehicle: "EV6", sharedVehicle: "EV6, IONIQ5" },
    { domain: "배터리", system: "BPA", modularSystem: "BATTERY PACK", part: "Upper Cover", spec: "Steel-Coated", moldCost: 320, targetVehicle: "EV6", sharedVehicle: "EV6" },
    { domain: "배터리", system: "BPA", modularSystem: "MODULE CASE", part: "Cell Holder", spec: "Plastic-Flame Retardant", moldCost: 85, targetVehicle: "EV6", sharedVehicle: "EV6, IONIQ6" },
    { domain: "시트/칵핏", system: "시트", modularSystem: "FR SEAT", part: "Heater Pad", spec: "Fast-Heating", moldCost: 12, targetVehicle: "EV6", sharedVehicle: "EV6, IONIQ5" },
    { domain: "섀시", system: "조향", modularSystem: "MDPS", part: "Motor Housing", spec: "Steel-Casting", moldCost: 65, targetVehicle: "Sportage", sharedVehicle: "Sportage, Tucson" },
    { domain: "섀시", system: "조향", modularSystem: "MDPS", part: "Steering Column", spec: "Collapsible", moldCost: 88, targetVehicle: "Sportage", sharedVehicle: "Sportage" },
    { domain: "의장", system: "필라트림", modularSystem: "INTERIOR TRIM", part: "A-Pillar Trim", spec: "Fabric-Wrapped", moldCost: 15, targetVehicle: "K8", sharedVehicle: "K8, G80" },
    { domain: "의장", system: "필라트림", modularSystem: "INTERIOR TRIM", part: "B-Pillar Trim", spec: "Plastic-Grain", moldCost: 12, targetVehicle: "K8", sharedVehicle: "K8" }
];

export default partsData;
